/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AboutWorkerD396fd5bffec1000100f44a5808f0005
 */
public class AboutWorkerD396fd5bffec1000100f44a5808f0005Test {
    private final AboutWorkerD396fd5bffec1000100f44a5808f0005 model = new AboutWorkerD396fd5bffec1000100f44a5808f0005();

    /**
     * Model tests for AboutWorkerD396fd5bffec1000100f44a5808f0005
     */
    @Test
    public void testAboutWorkerD396fd5bffec1000100f44a5808f0005() {
        // TODO: test AboutWorkerD396fd5bffec1000100f44a5808f0005
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

}
