/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CategorySummary88d272af423b100036e57ea69d570000AllOf
 */
public class CategorySummary88d272af423b100036e57ea69d570000AllOfTest {
    private final CategorySummary88d272af423b100036e57ea69d570000AllOf model = new CategorySummary88d272af423b100036e57ea69d570000AllOf();

    /**
     * Model tests for CategorySummary88d272af423b100036e57ea69d570000AllOf
     */
    @Test
    public void testCategorySummary88d272af423b100036e57ea69d570000AllOf() {
        // TODO: test CategorySummary88d272af423b100036e57ea69d570000AllOf
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
