/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e
 */
public class CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026eTest {
    private final CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e model = new CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e();

    /**
     * Model tests for CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e
     */
    @Test
    public void testCountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e() {
        // TODO: test CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
