/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FACETSMODELREFERENCEInnerValuesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FACETSMODELREFERENCEInner
 */
public class FACETSMODELREFERENCEInnerTest {
    private final FACETSMODELREFERENCEInner model = new FACETSMODELREFERENCEInner();

    /**
     * Model tests for FACETSMODELREFERENCEInner
     */
    @Test
    public void testFACETSMODELREFERENCEInner() {
        // TODO: test FACETSMODELREFERENCEInner
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'facetParameter'
     */
    @Test
    public void facetParameterTest() {
        // TODO: test facetParameter
    }

    /**
     * Test the property 'values'
     */
    @Test
    public void valuesTest() {
        // TODO: test values
    }

}
