/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FeedbackTemplate2b4c8a6ca069100035b859a141200001
 */
public class FeedbackTemplate2b4c8a6ca069100035b859a141200001Test {
    private final FeedbackTemplate2b4c8a6ca069100035b859a141200001 model = new FeedbackTemplate2b4c8a6ca069100035b859a141200001();

    /**
     * Model tests for FeedbackTemplate2b4c8a6ca069100035b859a141200001
     */
    @Test
    public void testFeedbackTemplate2b4c8a6ca069100035b859a141200001() {
        // TODO: test FeedbackTemplate2b4c8a6ca069100035b859a141200001
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

}
