/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FeedbackBadgeIconD4d355b2d3db100020b8608b75250016;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FeedbackBadgeDetail9eab868ca81410001402525d054211f7AllOf
 */
public class FeedbackBadgeDetail9eab868ca81410001402525d054211f7AllOfTest {
    private final FeedbackBadgeDetail9eab868ca81410001402525d054211f7AllOf model = new FeedbackBadgeDetail9eab868ca81410001402525d054211f7AllOf();

    /**
     * Model tests for FeedbackBadgeDetail9eab868ca81410001402525d054211f7AllOf
     */
    @Test
    public void testFeedbackBadgeDetail9eab868ca81410001402525d054211f7AllOf() {
        // TODO: test FeedbackBadgeDetail9eab868ca81410001402525d054211f7AllOf
    }

    /**
     * Test the property 'feedbackBadgeIcon'
     */
    @Test
    public void feedbackBadgeIconTest() {
        // TODO: test feedbackBadgeIcon
    }

    /**
     * Test the property 'workdayID'
     */
    @Test
    public void workdayIDTest() {
        // TODO: test workdayID
    }

    /**
     * Test the property 'feedbackBadgeID'
     */
    @Test
    public void feedbackBadgeIDTest() {
        // TODO: test feedbackBadgeID
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
