/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FeedbackResponder2f703c317dc910001c16504848720001;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FeedbackResponse2f703c317dc910001bd2de83d1590000
 */
public class FeedbackResponse2f703c317dc910001bd2de83d1590000Test {
    private final FeedbackResponse2f703c317dc910001bd2de83d1590000 model = new FeedbackResponse2f703c317dc910001bd2de83d1590000();

    /**
     * Model tests for FeedbackResponse2f703c317dc910001bd2de83d1590000
     */
    @Test
    public void testFeedbackResponse2f703c317dc910001bd2de83d1590000() {
        // TODO: test FeedbackResponse2f703c317dc910001bd2de83d1590000
    }

    /**
     * Test the property 'response'
     */
    @Test
    public void responseTest() {
        // TODO: test response
    }

    /**
     * Test the property 'feedbackDeclined'
     */
    @Test
    public void feedbackDeclinedTest() {
        // TODO: test feedbackDeclined
    }

    /**
     * Test the property 'feedbackDeclineReason'
     */
    @Test
    public void feedbackDeclineReasonTest() {
        // TODO: test feedbackDeclineReason
    }

    /**
     * Test the property 'feedbackResponder'
     */
    @Test
    public void feedbackResponderTest() {
        // TODO: test feedbackResponder
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
