/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BadgeAfd6ac52d62510001357f891ccfd0003;
import com.konfigthis.client.model.BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000;
import com.konfigthis.client.model.FromWorkerAfd6ac52d62510001357f891ccfd0001;
import com.konfigthis.client.model.GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302;
import com.konfigthis.client.model.RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000;
import com.konfigthis.client.model.RelatesTo9d12ad407f0f10001c3949add7d40000;
import com.konfigthis.client.model.ToWorkerF4946919a39f10000f03207b1f230000;
import com.konfigthis.client.model.WorkersToNotify9e478586f65410001035b6c26a4c0000;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
 */
public class FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOfTest {
    private final FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf model = new FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf();

    /**
     * Model tests for FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
     */
    @Test
    public void testFeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf() {
        // TODO: test FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000AllOf
    }

    /**
     * Test the property 'toWorker'
     */
    @Test
    public void toWorkerTest() {
        // TODO: test toWorker
    }

    /**
     * Test the property 'workersToNotify'
     */
    @Test
    public void workersToNotifyTest() {
        // TODO: test workersToNotify
    }

    /**
     * Test the property 'relatesTo'
     */
    @Test
    public void relatesToTest() {
        // TODO: test relatesTo
    }

    /**
     * Test the property 'businessProcessParameters'
     */
    @Test
    public void businessProcessParametersTest() {
        // TODO: test businessProcessParameters
    }

    /**
     * Test the property 'feedbackAlsoAbout'
     */
    @Test
    public void feedbackAlsoAboutTest() {
        // TODO: test feedbackAlsoAbout
    }

    /**
     * Test the property 'hiddenFromWorker'
     */
    @Test
    public void hiddenFromWorkerTest() {
        // TODO: test hiddenFromWorker
    }

    /**
     * Test the property 'hiddenFromManager'
     */
    @Test
    public void hiddenFromManagerTest() {
        // TODO: test hiddenFromManager
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'fromWorker'
     */
    @Test
    public void fromWorkerTest() {
        // TODO: test fromWorker
    }

    /**
     * Test the property 'badge'
     */
    @Test
    public void badgeTest() {
        // TODO: test badge
    }

    /**
     * Test the property 'relatedFeedbackEvents'
     */
    @Test
    public void relatedFeedbackEventsTest() {
        // TODO: test relatedFeedbackEvents
    }

    /**
     * Test the property 'feedbackGivenDate'
     */
    @Test
    public void feedbackGivenDateTest() {
        // TODO: test feedbackGivenDate
    }

    /**
     * Test the property 'showFeedbackProviderName'
     */
    @Test
    public void showFeedbackProviderNameTest() {
        // TODO: test showFeedbackProviderName
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
