/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000AllOf
 */
public class GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000AllOfTest {
    private final GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000AllOf model = new GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000AllOf();

    /**
     * Model tests for GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000AllOf
     */
    @Test
    public void testGigOpeningTalentTagAbe398d81e1e1000167d6197a9060000AllOf() {
        // TODO: test GigOpeningTalentTagAbe398d81e1e1000167d6197a9060000AllOf
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
