/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AboutWorkerD396fd5bffec1000100f44a5808f0005;
import com.konfigthis.client.model.BusinessProcessParametersD396fd5bffec1000100f440bde4c0001;
import com.konfigthis.client.model.RequestedByD396fd5bffec1000100f44a5808f0006;
import com.konfigthis.client.model.RequestedFeedbackCommentsD396fd5bffec10001393477e77870000;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
 */
public class GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOfTest {
    private final GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf model = new GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf();

    /**
     * Model tests for GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
     */
    @Test
    public void testGiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf() {
        // TODO: test GiveRequestedFeedbackDetailsD396fd5bffec10000e3eba1a70440000AllOf
    }

    /**
     * Test the property 'dueDate'
     */
    @Test
    public void dueDateTest() {
        // TODO: test dueDate
    }

    /**
     * Test the property 'feedbackGivenDate'
     */
    @Test
    public void feedbackGivenDateTest() {
        // TODO: test feedbackGivenDate
    }

    /**
     * Test the property 'feedbackCreationDate'
     */
    @Test
    public void feedbackCreationDateTest() {
        // TODO: test feedbackCreationDate
    }

    /**
     * Test the property 'requestedBy'
     */
    @Test
    public void requestedByTest() {
        // TODO: test requestedBy
    }

    /**
     * Test the property 'aboutWorker'
     */
    @Test
    public void aboutWorkerTest() {
        // TODO: test aboutWorker
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    public void expirationDateTest() {
        // TODO: test expirationDate
    }

    /**
     * Test the property 'displayNameofResponder'
     */
    @Test
    public void displayNameofResponderTest() {
        // TODO: test displayNameofResponder
    }

    /**
     * Test the property 'feedbackComments'
     */
    @Test
    public void feedbackCommentsTest() {
        // TODO: test feedbackComments
    }

    /**
     * Test the property 'businessProcessParameters'
     */
    @Test
    public void businessProcessParametersTest() {
        // TODO: test businessProcessParameters
    }

    /**
     * Test the property 'feedbackPrivate'
     */
    @Test
    public void feedbackPrivateTest() {
        // TODO: test feedbackPrivate
    }

    /**
     * Test the property 'feedbackConfidential'
     */
    @Test
    public void feedbackConfidentialTest() {
        // TODO: test feedbackConfidential
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
