/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ActivityStreamableItemSummary88d272af423b100036fc19a90e210000;
import com.konfigthis.client.model.AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000;
import com.konfigthis.client.model.CategorySummary88d272af423b100036e57ea69d570000;
import com.konfigthis.client.model.CreatedBy88d272af423b100036b561a7784b0000;
import com.konfigthis.client.model.RelatesToSummary2c793e888bcd100034b42ada01b20000;
import com.konfigthis.client.model.Status9df8579a128710001ac8e9879d1f0001;
import com.konfigthis.client.model.Supports9df8579a128710001ac8e9879d1f0000;
import com.konfigthis.client.model.Worker47e98fa91eee100017c2c78c80410000;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
 */
public class GoalsSummary2c793e888bcd100033e663075a2b0000AllOfTest {
    private final GoalsSummary2c793e888bcd100033e663075a2b0000AllOf model = new GoalsSummary2c793e888bcd100033e663075a2b0000AllOf();

    /**
     * Model tests for GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
     */
    @Test
    public void testGoalsSummary2c793e888bcd100033e663075a2b0000AllOf() {
        // TODO: test GoalsSummary2c793e888bcd100033e663075a2b0000AllOf
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'relatesTo'
     */
    @Test
    public void relatesToTest() {
        // TODO: test relatesTo
    }

    /**
     * Test the property 'activityStreamableItem'
     */
    @Test
    public void activityStreamableItemTest() {
        // TODO: test activityStreamableItem
    }

    /**
     * Test the property 'dueDate'
     */
    @Test
    public void dueDateTest() {
        // TODO: test dueDate
    }

    /**
     * Test the property 'associatedReviews'
     */
    @Test
    public void associatedReviewsTest() {
        // TODO: test associatedReviews
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'supports'
     */
    @Test
    public void supportsTest() {
        // TODO: test supports
    }

    /**
     * Test the property 'worker'
     */
    @Test
    public void workerTest() {
        // TODO: test worker
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'completedOn'
     */
    @Test
    public void completedOnTest() {
        // TODO: test completedOn
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
