/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobProfileJobViewFab4a151b24810000d511d61ee641262
 */
public class JobProfileJobViewFab4a151b24810000d511d61ee641262Test {
    private final JobProfileJobViewFab4a151b24810000d511d61ee641262 model = new JobProfileJobViewFab4a151b24810000d511d61ee641262();

    /**
     * Model tests for JobProfileJobViewFab4a151b24810000d511d61ee641262
     */
    @Test
    public void testJobProfileJobViewFab4a151b24810000d511d61ee641262() {
        // TODO: test JobProfileJobViewFab4a151b24810000d511d61ee641262
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
