/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobProfileB8ac205877fd10000ea9174f73c500aa
 */
public class JobProfileB8ac205877fd10000ea9174f73c500aaTest {
    private final JobProfileB8ac205877fd10000ea9174f73c500aa model = new JobProfileB8ac205877fd10000ea9174f73c500aa();

    /**
     * Model tests for JobProfileB8ac205877fd10000ea9174f73c500aa
     */
    @Test
    public void testJobProfileB8ac205877fd10000ea9174f73c500aa() {
        // TODO: test JobProfileB8ac205877fd10000ea9174f73c500aa
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
