/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobWorkspaceData1005157e3d631000144205466a6c13d3AllOf
 */
public class JobWorkspaceData1005157e3d631000144205466a6c13d3AllOfTest {
    private final JobWorkspaceData1005157e3d631000144205466a6c13d3AllOf model = new JobWorkspaceData1005157e3d631000144205466a6c13d3AllOf();

    /**
     * Model tests for JobWorkspaceData1005157e3d631000144205466a6c13d3AllOf
     */
    @Test
    public void testJobWorkspaceData1005157e3d631000144205466a6c13d3AllOf() {
        // TODO: test JobWorkspaceData1005157e3d631000144205466a6c13d3AllOf
    }

    /**
     * Test the property 'locationChain'
     */
    @Test
    public void locationChainTest() {
        // TODO: test locationChain
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
