/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000AllOf
 */
public class MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000AllOfTest {
    private final MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000AllOf model = new MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000AllOf();

    /**
     * Model tests for MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000AllOf
     */
    @Test
    public void testMultipleChoiceAnswers06c0300303a9100019828d5ca44a0000AllOf() {
        // TODO: test MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000AllOf
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
