/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PersonDataViewBe343791f59d100028d6a277ca8a0017
 */
public class PersonDataViewBe343791f59d100028d6a277ca8a0017Test {
    private final PersonDataViewBe343791f59d100028d6a277ca8a0017 model = new PersonDataViewBe343791f59d100028d6a277ca8a0017();

    /**
     * Model tests for PersonDataViewBe343791f59d100028d6a277ca8a0017
     */
    @Test
    public void testPersonDataViewBe343791f59d100028d6a277ca8a0017() {
        // TODO: test PersonDataViewBe343791f59d100028d6a277ca8a0017
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
