/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000AllOf
 */
public class QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000AllOfTest {
    private final QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000AllOf model = new QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000AllOf();

    /**
     * Model tests for QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000AllOf
     */
    @Test
    public void testQuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000AllOf() {
        // TODO: test QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000AllOf
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
