/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RelatesTo9d12ad407f0f10001c3949add7d40000
 */
public class RelatesTo9d12ad407f0f10001c3949add7d40000Test {
    private final RelatesTo9d12ad407f0f10001c3949add7d40000 model = new RelatesTo9d12ad407f0f10001c3949add7d40000();

    /**
     * Model tests for RelatesTo9d12ad407f0f10001c3949add7d40000
     */
    @Test
    public void testRelatesTo9d12ad407f0f10001c3949add7d40000() {
        // TODO: test RelatesTo9d12ad407f0f10001c3949add7d40000
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
