/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RelatesToSummary2c793e888bcd100034b42ada01b20000AllOf
 */
public class RelatesToSummary2c793e888bcd100034b42ada01b20000AllOfTest {
    private final RelatesToSummary2c793e888bcd100034b42ada01b20000AllOf model = new RelatesToSummary2c793e888bcd100034b42ada01b20000AllOf();

    /**
     * Model tests for RelatesToSummary2c793e888bcd100034b42ada01b20000AllOf
     */
    @Test
    public void testRelatesToSummary2c793e888bcd100034b42ada01b20000AllOf() {
        // TODO: test RelatesToSummary2c793e888bcd100034b42ada01b20000AllOf
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
