/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BusinessProcessParameters9708c966f04f10000e4ae9a03cf80001;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000AllOf
 */
public class RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000AllOfTest {
    private final RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000AllOf model = new RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000AllOf();

    /**
     * Model tests for RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000AllOf
     */
    @Test
    public void testRelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000AllOf() {
        // TODO: test RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000AllOf
    }

    /**
     * Test the property 'businessProcessParameters'
     */
    @Test
    public void businessProcessParametersTest() {
        // TODO: test businessProcessParameters
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
