/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BusinessProcessParameters2b4c8a6ca069100035b85907ae2c0000;
import com.konfigthis.client.model.FeedbackAbout2b4c8a6ca069100035b85907ae2c0002;
import com.konfigthis.client.model.FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000;
import com.konfigthis.client.model.FeedbackTemplate2b4c8a6ca069100035b859a141200001;
import com.konfigthis.client.model.RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000
 */
public class RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000Test {
    private final RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000 model = new RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000();

    /**
     * Model tests for RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000
     */
    @Test
    public void testRequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000() {
        // TODO: test RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000
    }

    /**
     * Test the property 'feedbackAbout'
     */
    @Test
    public void feedbackAboutTest() {
        // TODO: test feedbackAbout
    }

    /**
     * Test the property 'feedbackConfidential'
     */
    @Test
    public void feedbackConfidentialTest() {
        // TODO: test feedbackConfidential
    }

    /**
     * Test the property 'feedbackOverallStatus'
     */
    @Test
    public void feedbackOverallStatusTest() {
        // TODO: test feedbackOverallStatus
    }

    /**
     * Test the property 'showFeedbackProviderName'
     */
    @Test
    public void showFeedbackProviderNameTest() {
        // TODO: test showFeedbackProviderName
    }

    /**
     * Test the property 'requestDate'
     */
    @Test
    public void requestDateTest() {
        // TODO: test requestDate
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    public void expirationDateTest() {
        // TODO: test expirationDate
    }

    /**
     * Test the property 'feedbackQuestions'
     */
    @Test
    public void feedbackQuestionsTest() {
        // TODO: test feedbackQuestions
    }

    /**
     * Test the property 'feedbackTemplate'
     */
    @Test
    public void feedbackTemplateTest() {
        // TODO: test feedbackTemplate
    }

    /**
     * Test the property 'feedbackResponders'
     */
    @Test
    public void feedbackRespondersTest() {
        // TODO: test feedbackResponders
    }

    /**
     * Test the property 'businessProcessParameters'
     */
    @Test
    public void businessProcessParametersTest() {
        // TODO: test businessProcessParameters
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
