/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FeedbackResponse2f703c317dc910001bd2de83d1590000;
import com.konfigthis.client.model.QuestionMultipleChoiceFfdd5de32f7f100016c2c1e768f40000;
import com.konfigthis.client.model.QuestionTypeFfdd5de32f7f1000144df15bb77b0001;
import com.konfigthis.client.model.TalentTagFfdd5de32f7f100016c88e016ad20000;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000
 */
public class RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000Test {
    private final RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000 model = new RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000();

    /**
     * Model tests for RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000
     */
    @Test
    public void testRequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000() {
        // TODO: test RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000
    }

    /**
     * Test the property 'relatesTo'
     */
    @Test
    public void relatesToTest() {
        // TODO: test relatesTo
    }

    /**
     * Test the property 'question'
     */
    @Test
    public void questionTest() {
        // TODO: test question
    }

    /**
     * Test the property 'questionType'
     */
    @Test
    public void questionTypeTest() {
        // TODO: test questionType
    }

    /**
     * Test the property 'feedbackResponse'
     */
    @Test
    public void feedbackResponseTest() {
        // TODO: test feedbackResponse
    }

    /**
     * Test the property 'questionMultipleChoiceAnswers'
     */
    @Test
    public void questionMultipleChoiceAnswersTest() {
        // TODO: test questionMultipleChoiceAnswers
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
