/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FeedbackQuestionD396fd5bffec10001393481822cd0007;
import com.konfigthis.client.model.MultipleChoiceAnswers06c0300303a9100019828d5ca44a0000;
import com.konfigthis.client.model.PossibleMultipleChoiceAnswers4c60c128c16510000a59980041610000;
import com.konfigthis.client.model.QuestionType544916c1cd75100006c4f105d3f60000;
import com.konfigthis.client.model.RelatesToC836a10b43ed10000beb5b92b4c10000;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
 */
public class RequestedFeedbackCommentsD396fd5bffec10001393477e77870000Test {
    private final RequestedFeedbackCommentsD396fd5bffec10001393477e77870000 model = new RequestedFeedbackCommentsD396fd5bffec10001393477e77870000();

    /**
     * Model tests for RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
     */
    @Test
    public void testRequestedFeedbackCommentsD396fd5bffec10001393477e77870000() {
        // TODO: test RequestedFeedbackCommentsD396fd5bffec10001393477e77870000
    }

    /**
     * Test the property 'feedbackDeclined'
     */
    @Test
    public void feedbackDeclinedTest() {
        // TODO: test feedbackDeclined
    }

    /**
     * Test the property 'feedbackDeclineReason'
     */
    @Test
    public void feedbackDeclineReasonTest() {
        // TODO: test feedbackDeclineReason
    }

    /**
     * Test the property 'possibleMultipleChoiceAnswers'
     */
    @Test
    public void possibleMultipleChoiceAnswersTest() {
        // TODO: test possibleMultipleChoiceAnswers
    }

    /**
     * Test the property 'questionType'
     */
    @Test
    public void questionTypeTest() {
        // TODO: test questionType
    }

    /**
     * Test the property 'multipleChoiceAnswers'
     */
    @Test
    public void multipleChoiceAnswersTest() {
        // TODO: test multipleChoiceAnswers
    }

    /**
     * Test the property 'numericAnswer'
     */
    @Test
    public void numericAnswerTest() {
        // TODO: test numericAnswer
    }

    /**
     * Test the property 'dateAnswer'
     */
    @Test
    public void dateAnswerTest() {
        // TODO: test dateAnswer
    }

    /**
     * Test the property 'response'
     */
    @Test
    public void responseTest() {
        // TODO: test response
    }

    /**
     * Test the property 'relatesTo'
     */
    @Test
    public void relatesToTest() {
        // TODO: test relatesTo
    }

    /**
     * Test the property 'feedbackQuestion'
     */
    @Test
    public void feedbackQuestionTest() {
        // TODO: test feedbackQuestion
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
