/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkersToNotify9e478586f65410001035b6c26a4c0000
 */
public class WorkersToNotify9e478586f65410001035b6c26a4c0000Test {
    private final WorkersToNotify9e478586f65410001035b6c26a4c0000 model = new WorkersToNotify9e478586f65410001035b6c26a4c0000();

    /**
     * Model tests for WorkersToNotify9e478586f65410001035b6c26a4c0000
     */
    @Test
    public void testWorkersToNotify9e478586f65410001035b6c26a4c0000() {
        // TODO: test WorkersToNotify9e478586f65410001035b6c26a4c0000
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
