/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FeedbackBadgeIconD4d355b2d3db100020b8608b75250016;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * FeedbackBadgeDetail9eab868ca81410001402525d054211f7
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class FeedbackBadgeDetail9eab868ca81410001402525d054211f7 {
  public static final String SERIALIZED_NAME_FEEDBACK_BADGE_ICON = "feedbackBadgeIcon";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_BADGE_ICON)
  private FeedbackBadgeIconD4d355b2d3db100020b8608b75250016 feedbackBadgeIcon;

  public static final String SERIALIZED_NAME_WORKDAY_I_D = "workdayID";
  @SerializedName(SERIALIZED_NAME_WORKDAY_I_D)
  private String workdayID;

  public static final String SERIALIZED_NAME_FEEDBACK_BADGE_I_D = "feedbackBadgeID";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_BADGE_I_D)
  private String feedbackBadgeID;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public FeedbackBadgeDetail9eab868ca81410001402525d054211f7() {
  }

  public FeedbackBadgeDetail9eab868ca81410001402525d054211f7 feedbackBadgeIcon(FeedbackBadgeIconD4d355b2d3db100020b8608b75250016 feedbackBadgeIcon) {
    
    
    
    
    this.feedbackBadgeIcon = feedbackBadgeIcon;
    return this;
  }

   /**
   * Get feedbackBadgeIcon
   * @return feedbackBadgeIcon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FeedbackBadgeIconD4d355b2d3db100020b8608b75250016 getFeedbackBadgeIcon() {
    return feedbackBadgeIcon;
  }


  public void setFeedbackBadgeIcon(FeedbackBadgeIconD4d355b2d3db100020b8608b75250016 feedbackBadgeIcon) {
    
    
    
    this.feedbackBadgeIcon = feedbackBadgeIcon;
  }


  public FeedbackBadgeDetail9eab868ca81410001402525d054211f7 workdayID(String workdayID) {
    
    
    
    
    this.workdayID = workdayID;
    return this;
  }

   /**
   * Returns the Workday ID for a given object.
   * @return workdayID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "Returns the Workday ID for a given object.")

  public String getWorkdayID() {
    return workdayID;
  }


  public void setWorkdayID(String workdayID) {
    
    
    
    this.workdayID = workdayID;
  }


  public FeedbackBadgeDetail9eab868ca81410001402525d054211f7 feedbackBadgeID(String feedbackBadgeID) {
    
    
    
    
    this.feedbackBadgeID = feedbackBadgeID;
    return this;
  }

   /**
   * The Reference ID to use for lookups within our Workday Web Services. For supervisory organizations, this is also the &#39;Organization ID&#39;
   * @return feedbackBadgeID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The Reference ID to use for lookups within our Workday Web Services. For supervisory organizations, this is also the 'Organization ID'")

  public String getFeedbackBadgeID() {
    return feedbackBadgeID;
  }


  public void setFeedbackBadgeID(String feedbackBadgeID) {
    
    
    
    this.feedbackBadgeID = feedbackBadgeID;
  }


  public FeedbackBadgeDetail9eab868ca81410001402525d054211f7 name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * The name of this feedback badge.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The name of this feedback badge.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the FeedbackBadgeDetail9eab868ca81410001402525d054211f7 instance itself
   */
  public FeedbackBadgeDetail9eab868ca81410001402525d054211f7 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeedbackBadgeDetail9eab868ca81410001402525d054211f7 feedbackBadgeDetail9eab868ca81410001402525d054211f7 = (FeedbackBadgeDetail9eab868ca81410001402525d054211f7) o;
    return Objects.equals(this.feedbackBadgeIcon, feedbackBadgeDetail9eab868ca81410001402525d054211f7.feedbackBadgeIcon) &&
        Objects.equals(this.workdayID, feedbackBadgeDetail9eab868ca81410001402525d054211f7.workdayID) &&
        Objects.equals(this.feedbackBadgeID, feedbackBadgeDetail9eab868ca81410001402525d054211f7.feedbackBadgeID) &&
        Objects.equals(this.name, feedbackBadgeDetail9eab868ca81410001402525d054211f7.name)&&
        Objects.equals(this.additionalProperties, feedbackBadgeDetail9eab868ca81410001402525d054211f7.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feedbackBadgeIcon, workdayID, feedbackBadgeID, name, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeedbackBadgeDetail9eab868ca81410001402525d054211f7 {\n");
    sb.append("    feedbackBadgeIcon: ").append(toIndentedString(feedbackBadgeIcon)).append("\n");
    sb.append("    workdayID: ").append(toIndentedString(workdayID)).append("\n");
    sb.append("    feedbackBadgeID: ").append(toIndentedString(feedbackBadgeID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("feedbackBadgeIcon");
    openapiFields.add("workdayID");
    openapiFields.add("feedbackBadgeID");
    openapiFields.add("name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to FeedbackBadgeDetail9eab868ca81410001402525d054211f7
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!FeedbackBadgeDetail9eab868ca81410001402525d054211f7.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FeedbackBadgeDetail9eab868ca81410001402525d054211f7 is not found in the empty JSON string", FeedbackBadgeDetail9eab868ca81410001402525d054211f7.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `feedbackBadgeIcon`
      if (jsonObj.get("feedbackBadgeIcon") != null && !jsonObj.get("feedbackBadgeIcon").isJsonNull()) {
        FeedbackBadgeIconD4d355b2d3db100020b8608b75250016.validateJsonObject(jsonObj.getAsJsonObject("feedbackBadgeIcon"));
      }
      if ((jsonObj.get("workdayID") != null && !jsonObj.get("workdayID").isJsonNull()) && !jsonObj.get("workdayID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `workdayID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("workdayID").toString()));
      }
      if ((jsonObj.get("feedbackBadgeID") != null && !jsonObj.get("feedbackBadgeID").isJsonNull()) && !jsonObj.get("feedbackBadgeID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `feedbackBadgeID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("feedbackBadgeID").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FeedbackBadgeDetail9eab868ca81410001402525d054211f7.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FeedbackBadgeDetail9eab868ca81410001402525d054211f7' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FeedbackBadgeDetail9eab868ca81410001402525d054211f7> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FeedbackBadgeDetail9eab868ca81410001402525d054211f7.class));

       return (TypeAdapter<T>) new TypeAdapter<FeedbackBadgeDetail9eab868ca81410001402525d054211f7>() {
           @Override
           public void write(JsonWriter out, FeedbackBadgeDetail9eab868ca81410001402525d054211f7 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public FeedbackBadgeDetail9eab868ca81410001402525d054211f7 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             FeedbackBadgeDetail9eab868ca81410001402525d054211f7 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FeedbackBadgeDetail9eab868ca81410001402525d054211f7 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FeedbackBadgeDetail9eab868ca81410001402525d054211f7
  * @throws IOException if the JSON string is invalid with respect to FeedbackBadgeDetail9eab868ca81410001402525d054211f7
  */
  public static FeedbackBadgeDetail9eab868ca81410001402525d054211f7 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FeedbackBadgeDetail9eab868ca81410001402525d054211f7.class);
  }

 /**
  * Convert an instance of FeedbackBadgeDetail9eab868ca81410001402525d054211f7 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

