/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BadgeAfd6ac52d62510001357f891ccfd0003;
import com.konfigthis.client.model.BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000;
import com.konfigthis.client.model.FromWorkerAfd6ac52d62510001357f891ccfd0001;
import com.konfigthis.client.model.GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302;
import com.konfigthis.client.model.RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000;
import com.konfigthis.client.model.RelatesTo9d12ad407f0f10001c3949add7d40000;
import com.konfigthis.client.model.ToWorkerF4946919a39f10000f03207b1f230000;
import com.konfigthis.client.model.WorkersToNotify9e478586f65410001035b6c26a4c0000;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 {
  public static final String SERIALIZED_NAME_TO_WORKER = "toWorker";
  @SerializedName(SERIALIZED_NAME_TO_WORKER)
  private ToWorkerF4946919a39f10000f03207b1f230000 toWorker;

  public static final String SERIALIZED_NAME_WORKERS_TO_NOTIFY = "workersToNotify";
  @SerializedName(SERIALIZED_NAME_WORKERS_TO_NOTIFY)
  private List<WorkersToNotify9e478586f65410001035b6c26a4c0000> workersToNotify = null;

  public static final String SERIALIZED_NAME_RELATES_TO = "relatesTo";
  @SerializedName(SERIALIZED_NAME_RELATES_TO)
  private RelatesTo9d12ad407f0f10001c3949add7d40000 relatesTo;

  public static final String SERIALIZED_NAME_BUSINESS_PROCESS_PARAMETERS = "businessProcessParameters";
  @SerializedName(SERIALIZED_NAME_BUSINESS_PROCESS_PARAMETERS)
  private BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000 businessProcessParameters;

  public static final String SERIALIZED_NAME_FEEDBACK_ALSO_ABOUT = "feedbackAlsoAbout";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_ALSO_ABOUT)
  private List<GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302> feedbackAlsoAbout = null;

  public static final String SERIALIZED_NAME_HIDDEN_FROM_WORKER = "hiddenFromWorker";
  @SerializedName(SERIALIZED_NAME_HIDDEN_FROM_WORKER)
  private Boolean hiddenFromWorker;

  public static final String SERIALIZED_NAME_HIDDEN_FROM_MANAGER = "hiddenFromManager";
  @SerializedName(SERIALIZED_NAME_HIDDEN_FROM_MANAGER)
  private Boolean hiddenFromManager;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;

  public static final String SERIALIZED_NAME_FROM_WORKER = "fromWorker";
  @SerializedName(SERIALIZED_NAME_FROM_WORKER)
  private FromWorkerAfd6ac52d62510001357f891ccfd0001 fromWorker;

  public static final String SERIALIZED_NAME_BADGE = "badge";
  @SerializedName(SERIALIZED_NAME_BADGE)
  private BadgeAfd6ac52d62510001357f891ccfd0003 badge;

  public static final String SERIALIZED_NAME_RELATED_FEEDBACK_EVENTS = "relatedFeedbackEvents";
  @SerializedName(SERIALIZED_NAME_RELATED_FEEDBACK_EVENTS)
  private List<RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000> relatedFeedbackEvents = null;

  public static final String SERIALIZED_NAME_FEEDBACK_GIVEN_DATE = "feedbackGivenDate";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_GIVEN_DATE)
  private LocalDate feedbackGivenDate;

  public static final String SERIALIZED_NAME_SHOW_FEEDBACK_PROVIDER_NAME = "showFeedbackProviderName";
  @SerializedName(SERIALIZED_NAME_SHOW_FEEDBACK_PROVIDER_NAME)
  private Boolean showFeedbackProviderName;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_DESCRIPTOR = "descriptor";
  @SerializedName(SERIALIZED_NAME_DESCRIPTOR)
  private String descriptor;

  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000() {
  }

  
  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000(
     List<RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000> relatedFeedbackEvents
  ) {
    this();
    this.relatedFeedbackEvents = relatedFeedbackEvents;
  }

  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 toWorker(ToWorkerF4946919a39f10000f03207b1f230000 toWorker) {
    
    
    
    
    this.toWorker = toWorker;
    return this;
  }

   /**
   * Get toWorker
   * @return toWorker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ToWorkerF4946919a39f10000f03207b1f230000 getToWorker() {
    return toWorker;
  }


  public void setToWorker(ToWorkerF4946919a39f10000f03207b1f230000 toWorker) {
    
    
    
    this.toWorker = toWorker;
  }


  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 workersToNotify(List<WorkersToNotify9e478586f65410001035b6c26a4c0000> workersToNotify) {
    
    
    
    
    this.workersToNotify = workersToNotify;
    return this;
  }

  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 addWorkersToNotifyItem(WorkersToNotify9e478586f65410001035b6c26a4c0000 workersToNotifyItem) {
    if (this.workersToNotify == null) {
      this.workersToNotify = new ArrayList<>();
    }
    this.workersToNotify.add(workersToNotifyItem);
    return this;
  }

   /**
   * The workers that were selected to be notified of the feedback given event.
   * @return workersToNotify
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The workers that were selected to be notified of the feedback given event.")

  public List<WorkersToNotify9e478586f65410001035b6c26a4c0000> getWorkersToNotify() {
    return workersToNotify;
  }


  public void setWorkersToNotify(List<WorkersToNotify9e478586f65410001035b6c26a4c0000> workersToNotify) {
    
    
    
    this.workersToNotify = workersToNotify;
  }


  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 relatesTo(RelatesTo9d12ad407f0f10001c3949add7d40000 relatesTo) {
    
    
    
    
    this.relatesTo = relatesTo;
    return this;
  }

   /**
   * Get relatesTo
   * @return relatesTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public RelatesTo9d12ad407f0f10001c3949add7d40000 getRelatesTo() {
    return relatesTo;
  }


  public void setRelatesTo(RelatesTo9d12ad407f0f10001c3949add7d40000 relatesTo) {
    
    
    
    this.relatesTo = relatesTo;
  }


  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 businessProcessParameters(BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000 businessProcessParameters) {
    
    
    
    
    this.businessProcessParameters = businessProcessParameters;
    return this;
  }

   /**
   * Get businessProcessParameters
   * @return businessProcessParameters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000 getBusinessProcessParameters() {
    return businessProcessParameters;
  }


  public void setBusinessProcessParameters(BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000 businessProcessParameters) {
    
    
    
    this.businessProcessParameters = businessProcessParameters;
  }


  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 feedbackAlsoAbout(List<GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302> feedbackAlsoAbout) {
    
    
    
    
    this.feedbackAlsoAbout = feedbackAlsoAbout;
    return this;
  }

  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 addFeedbackAlsoAboutItem(GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302 feedbackAlsoAboutItem) {
    if (this.feedbackAlsoAbout == null) {
      this.feedbackAlsoAbout = new ArrayList<>();
    }
    this.feedbackAlsoAbout.add(feedbackAlsoAboutItem);
    return this;
  }

   /**
   * The other workers this feedback event is about.
   * @return feedbackAlsoAbout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The other workers this feedback event is about.")

  public List<GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302> getFeedbackAlsoAbout() {
    return feedbackAlsoAbout;
  }


  public void setFeedbackAlsoAbout(List<GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302> feedbackAlsoAbout) {
    
    
    
    this.feedbackAlsoAbout = feedbackAlsoAbout;
  }


  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 hiddenFromWorker(Boolean hiddenFromWorker) {
    
    
    
    
    this.hiddenFromWorker = hiddenFromWorker;
    return this;
  }

   /**
   * True if the feedback event is confidential between the feedback provider and the manager. Workers don&#39;t see confidential feedback.
   * @return hiddenFromWorker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "True if the feedback event is confidential between the feedback provider and the manager. Workers don't see confidential feedback.")

  public Boolean getHiddenFromWorker() {
    return hiddenFromWorker;
  }


  public void setHiddenFromWorker(Boolean hiddenFromWorker) {
    
    
    
    this.hiddenFromWorker = hiddenFromWorker;
  }


  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 hiddenFromManager(Boolean hiddenFromManager) {
    
    
    
    
    this.hiddenFromManager = hiddenFromManager;
    return this;
  }

   /**
   * True if the feedback event is private between the feedback provider and the worker. Private feedback isn&#39;t shared with managers.
   * @return hiddenFromManager
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "True if the feedback event is private between the feedback provider and the worker. Private feedback isn't shared with managers.")

  public Boolean getHiddenFromManager() {
    return hiddenFromManager;
  }


  public void setHiddenFromManager(Boolean hiddenFromManager) {
    
    
    
    this.hiddenFromManager = hiddenFromManager;
  }


  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 comment(String comment) {
    
    
    
    
    this.comment = comment;
    return this;
  }

   /**
   * The comment text for an anytime feedback event.
   * @return comment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The comment text for an anytime feedback event.")

  public String getComment() {
    return comment;
  }


  public void setComment(String comment) {
    
    
    
    this.comment = comment;
  }


  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 fromWorker(FromWorkerAfd6ac52d62510001357f891ccfd0001 fromWorker) {
    
    
    
    
    this.fromWorker = fromWorker;
    return this;
  }

   /**
   * Get fromWorker
   * @return fromWorker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FromWorkerAfd6ac52d62510001357f891ccfd0001 getFromWorker() {
    return fromWorker;
  }


  public void setFromWorker(FromWorkerAfd6ac52d62510001357f891ccfd0001 fromWorker) {
    
    
    
    this.fromWorker = fromWorker;
  }


  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 badge(BadgeAfd6ac52d62510001357f891ccfd0003 badge) {
    
    
    
    
    this.badge = badge;
    return this;
  }

   /**
   * Get badge
   * @return badge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BadgeAfd6ac52d62510001357f891ccfd0003 getBadge() {
    return badge;
  }


  public void setBadge(BadgeAfd6ac52d62510001357f891ccfd0003 badge) {
    
    
    
    this.badge = badge;
  }


   /**
   * The anytime feedback events for the multiple recipients event.
   * @return relatedFeedbackEvents
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The anytime feedback events for the multiple recipients event.")

  public List<RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000> getRelatedFeedbackEvents() {
    return relatedFeedbackEvents;
  }




  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 feedbackGivenDate(LocalDate feedbackGivenDate) {
    
    
    
    
    this.feedbackGivenDate = feedbackGivenDate;
    return this;
  }

   /**
   * The date the feedback was provided.
   * @return feedbackGivenDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date the feedback was provided.")

  public LocalDate getFeedbackGivenDate() {
    return feedbackGivenDate;
  }


  public void setFeedbackGivenDate(LocalDate feedbackGivenDate) {
    
    
    
    this.feedbackGivenDate = feedbackGivenDate;
  }


  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 showFeedbackProviderName(Boolean showFeedbackProviderName) {
    
    
    
    
    this.showFeedbackProviderName = showFeedbackProviderName;
    return this;
  }

   /**
   * True if the feedback provider&#39;s name has chosen to be displayed. Names not chosen to be displayed are not shared.
   * @return showFeedbackProviderName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "True if the feedback provider's name has chosen to be displayed. Names not chosen to be displayed are not shared.")

  public Boolean getShowFeedbackProviderName() {
    return showFeedbackProviderName;
  }


  public void setShowFeedbackProviderName(Boolean showFeedbackProviderName) {
    
    
    
    this.showFeedbackProviderName = showFeedbackProviderName;
  }


  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 href(String href) {
    
    
    
    
    this.href = href;
    return this;
  }

   /**
   * A link to the instance
   * @return href
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A link to the instance")

  public String getHref() {
    return href;
  }


  public void setHref(String href) {
    
    
    
    this.href = href;
  }


  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Id of the instance
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Id of the instance")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 descriptor(String descriptor) {
    
    
    
    
    this.descriptor = descriptor;
    return this;
  }

   /**
   * A preview of the instance
   * @return descriptor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit ame", value = "A preview of the instance")

  public String getDescriptor() {
    return descriptor;
  }


  public void setDescriptor(String descriptor) {
    
    
    
    this.descriptor = descriptor;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 instance itself
   */
  public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 feedbackEventDetailAfd6ac52d62510001086b5c85cd50000 = (FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000) o;
    return Objects.equals(this.toWorker, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.toWorker) &&
        Objects.equals(this.workersToNotify, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.workersToNotify) &&
        Objects.equals(this.relatesTo, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.relatesTo) &&
        Objects.equals(this.businessProcessParameters, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.businessProcessParameters) &&
        Objects.equals(this.feedbackAlsoAbout, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.feedbackAlsoAbout) &&
        Objects.equals(this.hiddenFromWorker, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.hiddenFromWorker) &&
        Objects.equals(this.hiddenFromManager, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.hiddenFromManager) &&
        Objects.equals(this.comment, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.comment) &&
        Objects.equals(this.fromWorker, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.fromWorker) &&
        Objects.equals(this.badge, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.badge) &&
        Objects.equals(this.relatedFeedbackEvents, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.relatedFeedbackEvents) &&
        Objects.equals(this.feedbackGivenDate, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.feedbackGivenDate) &&
        Objects.equals(this.showFeedbackProviderName, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.showFeedbackProviderName) &&
        Objects.equals(this.href, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.href) &&
        Objects.equals(this.id, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.id) &&
        Objects.equals(this.descriptor, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.descriptor)&&
        Objects.equals(this.additionalProperties, feedbackEventDetailAfd6ac52d62510001086b5c85cd50000.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(toWorker, workersToNotify, relatesTo, businessProcessParameters, feedbackAlsoAbout, hiddenFromWorker, hiddenFromManager, comment, fromWorker, badge, relatedFeedbackEvents, feedbackGivenDate, showFeedbackProviderName, href, id, descriptor, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 {\n");
    sb.append("    toWorker: ").append(toIndentedString(toWorker)).append("\n");
    sb.append("    workersToNotify: ").append(toIndentedString(workersToNotify)).append("\n");
    sb.append("    relatesTo: ").append(toIndentedString(relatesTo)).append("\n");
    sb.append("    businessProcessParameters: ").append(toIndentedString(businessProcessParameters)).append("\n");
    sb.append("    feedbackAlsoAbout: ").append(toIndentedString(feedbackAlsoAbout)).append("\n");
    sb.append("    hiddenFromWorker: ").append(toIndentedString(hiddenFromWorker)).append("\n");
    sb.append("    hiddenFromManager: ").append(toIndentedString(hiddenFromManager)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    fromWorker: ").append(toIndentedString(fromWorker)).append("\n");
    sb.append("    badge: ").append(toIndentedString(badge)).append("\n");
    sb.append("    relatedFeedbackEvents: ").append(toIndentedString(relatedFeedbackEvents)).append("\n");
    sb.append("    feedbackGivenDate: ").append(toIndentedString(feedbackGivenDate)).append("\n");
    sb.append("    showFeedbackProviderName: ").append(toIndentedString(showFeedbackProviderName)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    descriptor: ").append(toIndentedString(descriptor)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("toWorker");
    openapiFields.add("workersToNotify");
    openapiFields.add("relatesTo");
    openapiFields.add("businessProcessParameters");
    openapiFields.add("feedbackAlsoAbout");
    openapiFields.add("hiddenFromWorker");
    openapiFields.add("hiddenFromManager");
    openapiFields.add("comment");
    openapiFields.add("fromWorker");
    openapiFields.add("badge");
    openapiFields.add("relatedFeedbackEvents");
    openapiFields.add("feedbackGivenDate");
    openapiFields.add("showFeedbackProviderName");
    openapiFields.add("href");
    openapiFields.add("id");
    openapiFields.add("descriptor");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 is not found in the empty JSON string", FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `toWorker`
      if (jsonObj.get("toWorker") != null && !jsonObj.get("toWorker").isJsonNull()) {
        ToWorkerF4946919a39f10000f03207b1f230000.validateJsonObject(jsonObj.getAsJsonObject("toWorker"));
      }
      if (jsonObj.get("workersToNotify") != null && !jsonObj.get("workersToNotify").isJsonNull()) {
        JsonArray jsonArrayworkersToNotify = jsonObj.getAsJsonArray("workersToNotify");
        if (jsonArrayworkersToNotify != null) {
          // ensure the json data is an array
          if (!jsonObj.get("workersToNotify").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `workersToNotify` to be an array in the JSON string but got `%s`", jsonObj.get("workersToNotify").toString()));
          }

          // validate the optional field `workersToNotify` (array)
          for (int i = 0; i < jsonArrayworkersToNotify.size(); i++) {
            WorkersToNotify9e478586f65410001035b6c26a4c0000.validateJsonObject(jsonArrayworkersToNotify.get(i).getAsJsonObject());
          };
        }
      }
      // validate the optional field `relatesTo`
      if (jsonObj.get("relatesTo") != null && !jsonObj.get("relatesTo").isJsonNull()) {
        RelatesTo9d12ad407f0f10001c3949add7d40000.validateJsonObject(jsonObj.getAsJsonObject("relatesTo"));
      }
      // validate the optional field `businessProcessParameters`
      if (jsonObj.get("businessProcessParameters") != null && !jsonObj.get("businessProcessParameters").isJsonNull()) {
        BusinessProcessParametersAfd6ac52d6251000117d0a60ed8b0000.validateJsonObject(jsonObj.getAsJsonObject("businessProcessParameters"));
      }
      if (jsonObj.get("feedbackAlsoAbout") != null && !jsonObj.get("feedbackAlsoAbout").isJsonNull()) {
        JsonArray jsonArrayfeedbackAlsoAbout = jsonObj.getAsJsonArray("feedbackAlsoAbout");
        if (jsonArrayfeedbackAlsoAbout != null) {
          // ensure the json data is an array
          if (!jsonObj.get("feedbackAlsoAbout").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `feedbackAlsoAbout` to be an array in the JSON string but got `%s`", jsonObj.get("feedbackAlsoAbout").toString()));
          }

          // validate the optional field `feedbackAlsoAbout` (array)
          for (int i = 0; i < jsonArrayfeedbackAlsoAbout.size(); i++) {
            GetWorkersFeedbackAlsoAbout3ab333661034100010b5635b2f7a0302.validateJsonObject(jsonArrayfeedbackAlsoAbout.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("comment") != null && !jsonObj.get("comment").isJsonNull()) && !jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
      // validate the optional field `fromWorker`
      if (jsonObj.get("fromWorker") != null && !jsonObj.get("fromWorker").isJsonNull()) {
        FromWorkerAfd6ac52d62510001357f891ccfd0001.validateJsonObject(jsonObj.getAsJsonObject("fromWorker"));
      }
      // validate the optional field `badge`
      if (jsonObj.get("badge") != null && !jsonObj.get("badge").isJsonNull()) {
        BadgeAfd6ac52d62510001357f891ccfd0003.validateJsonObject(jsonObj.getAsJsonObject("badge"));
      }
      if (jsonObj.get("relatedFeedbackEvents") != null && !jsonObj.get("relatedFeedbackEvents").isJsonNull()) {
        JsonArray jsonArrayrelatedFeedbackEvents = jsonObj.getAsJsonArray("relatedFeedbackEvents");
        if (jsonArrayrelatedFeedbackEvents != null) {
          // ensure the json data is an array
          if (!jsonObj.get("relatedFeedbackEvents").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `relatedFeedbackEvents` to be an array in the JSON string but got `%s`", jsonObj.get("relatedFeedbackEvents").toString()));
          }

          // validate the optional field `relatedFeedbackEvents` (array)
          for (int i = 0; i < jsonArrayrelatedFeedbackEvents.size(); i++) {
            RelatedFeedbackEvents9708c966f04f10000e1e9b7f9a5c0000.validateJsonObject(jsonArrayrelatedFeedbackEvents.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("href") != null && !jsonObj.get("href").isJsonNull()) && !jsonObj.get("href").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `href` to be a primitive type in the JSON string but got `%s`", jsonObj.get("href").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("descriptor") != null && !jsonObj.get("descriptor").isJsonNull()) && !jsonObj.get("descriptor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `descriptor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("descriptor").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000.class));

       return (TypeAdapter<T>) new TypeAdapter<FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000>() {
           @Override
           public void write(JsonWriter out, FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000
  * @throws IOException if the JSON string is invalid with respect to FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000
  */
  public static FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000.class);
  }

 /**
  * Convert an instance of FeedbackEventDetailAfd6ac52d62510001086b5c85cd50000 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

