/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ActivityStreamableItemSummary88d272af423b100036fc19a90e210000;
import com.konfigthis.client.model.AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000;
import com.konfigthis.client.model.CategorySummary88d272af423b100036e57ea69d570000;
import com.konfigthis.client.model.CreatedBy88d272af423b100036b561a7784b0000;
import com.konfigthis.client.model.RelatesToSummary2c793e888bcd100034b42ada01b20000;
import com.konfigthis.client.model.Status9df8579a128710001ac8e9879d1f0001;
import com.konfigthis.client.model.Supports9df8579a128710001ac8e9879d1f0000;
import com.konfigthis.client.model.Worker47e98fa91eee100017c2c78c80410000;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * GoalsSummary2c793e888bcd100033e663075a2b0000
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class GoalsSummary2c793e888bcd100033e663075a2b0000 {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_RELATES_TO = "relatesTo";
  @SerializedName(SERIALIZED_NAME_RELATES_TO)
  private List<RelatesToSummary2c793e888bcd100034b42ada01b20000> relatesTo = null;

  public static final String SERIALIZED_NAME_ACTIVITY_STREAMABLE_ITEM = "activityStreamableItem";
  @SerializedName(SERIALIZED_NAME_ACTIVITY_STREAMABLE_ITEM)
  private List<ActivityStreamableItemSummary88d272af423b100036fc19a90e210000> activityStreamableItem = null;

  public static final String SERIALIZED_NAME_DUE_DATE = "dueDate";
  @SerializedName(SERIALIZED_NAME_DUE_DATE)
  private LocalDate dueDate;

  public static final String SERIALIZED_NAME_ASSOCIATED_REVIEWS = "associatedReviews";
  @SerializedName(SERIALIZED_NAME_ASSOCIATED_REVIEWS)
  private List<AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000> associatedReviews = null;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private List<CategorySummary88d272af423b100036e57ea69d570000> category = null;

  public static final String SERIALIZED_NAME_SUPPORTS = "supports";
  @SerializedName(SERIALIZED_NAME_SUPPORTS)
  private Supports9df8579a128710001ac8e9879d1f0000 supports;

  public static final String SERIALIZED_NAME_WORKER = "worker";
  @SerializedName(SERIALIZED_NAME_WORKER)
  private Worker47e98fa91eee100017c2c78c80410000 worker;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private Status9df8579a128710001ac8e9879d1f0001 status;

  public static final String SERIALIZED_NAME_COMPLETED_ON = "completedOn";
  @SerializedName(SERIALIZED_NAME_COMPLETED_ON)
  private LocalDate completedOn;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private CreatedBy88d272af423b100036b561a7784b0000 createdBy;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public GoalsSummary2c793e888bcd100033e663075a2b0000() {
  }

  public GoalsSummary2c793e888bcd100033e663075a2b0000 description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * The description of the goal.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The description of the goal.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public GoalsSummary2c793e888bcd100033e663075a2b0000 name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * The name of the goal.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The name of the goal.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public GoalsSummary2c793e888bcd100033e663075a2b0000 relatesTo(List<RelatesToSummary2c793e888bcd100034b42ada01b20000> relatesTo) {
    
    
    
    
    this.relatesTo = relatesTo;
    return this;
  }

  public GoalsSummary2c793e888bcd100033e663075a2b0000 addRelatesToItem(RelatesToSummary2c793e888bcd100034b42ada01b20000 relatesToItem) {
    if (this.relatesTo == null) {
      this.relatesTo = new ArrayList<>();
    }
    this.relatesTo.add(relatesToItem);
    return this;
  }

   /**
   * The tags included with the goal.
   * @return relatesTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The tags included with the goal.")

  public List<RelatesToSummary2c793e888bcd100034b42ada01b20000> getRelatesTo() {
    return relatesTo;
  }


  public void setRelatesTo(List<RelatesToSummary2c793e888bcd100034b42ada01b20000> relatesTo) {
    
    
    
    this.relatesTo = relatesTo;
  }


  public GoalsSummary2c793e888bcd100033e663075a2b0000 activityStreamableItem(List<ActivityStreamableItemSummary88d272af423b100036fc19a90e210000> activityStreamableItem) {
    
    
    
    
    this.activityStreamableItem = activityStreamableItem;
    return this;
  }

  public GoalsSummary2c793e888bcd100033e663075a2b0000 addActivityStreamableItemItem(ActivityStreamableItemSummary88d272af423b100036fc19a90e210000 activityStreamableItemItem) {
    if (this.activityStreamableItem == null) {
      this.activityStreamableItem = new ArrayList<>();
    }
    this.activityStreamableItem.add(activityStreamableItemItem);
    return this;
  }

   /**
   * The activity stream associated with the goal.
   * @return activityStreamableItem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The activity stream associated with the goal.")

  public List<ActivityStreamableItemSummary88d272af423b100036fc19a90e210000> getActivityStreamableItem() {
    return activityStreamableItem;
  }


  public void setActivityStreamableItem(List<ActivityStreamableItemSummary88d272af423b100036fc19a90e210000> activityStreamableItem) {
    
    
    
    this.activityStreamableItem = activityStreamableItem;
  }


  public GoalsSummary2c793e888bcd100033e663075a2b0000 dueDate(LocalDate dueDate) {
    
    
    
    
    this.dueDate = dueDate;
    return this;
  }

   /**
   * The date when the goal is due.
   * @return dueDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date when the goal is due.")

  public LocalDate getDueDate() {
    return dueDate;
  }


  public void setDueDate(LocalDate dueDate) {
    
    
    
    this.dueDate = dueDate;
  }


  public GoalsSummary2c793e888bcd100033e663075a2b0000 associatedReviews(List<AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000> associatedReviews) {
    
    
    
    
    this.associatedReviews = associatedReviews;
    return this;
  }

  public GoalsSummary2c793e888bcd100033e663075a2b0000 addAssociatedReviewsItem(AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000 associatedReviewsItem) {
    if (this.associatedReviews == null) {
      this.associatedReviews = new ArrayList<>();
    }
    this.associatedReviews.add(associatedReviewsItem);
    return this;
  }

   /**
   * The associated reviews with the goal.
   * @return associatedReviews
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The associated reviews with the goal.")

  public List<AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000> getAssociatedReviews() {
    return associatedReviews;
  }


  public void setAssociatedReviews(List<AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000> associatedReviews) {
    
    
    
    this.associatedReviews = associatedReviews;
  }


  public GoalsSummary2c793e888bcd100033e663075a2b0000 category(List<CategorySummary88d272af423b100036e57ea69d570000> category) {
    
    
    
    
    this.category = category;
    return this;
  }

  public GoalsSummary2c793e888bcd100033e663075a2b0000 addCategoryItem(CategorySummary88d272af423b100036e57ea69d570000 categoryItem) {
    if (this.category == null) {
      this.category = new ArrayList<>();
    }
    this.category.add(categoryItem);
    return this;
  }

   /**
   * The category of the goal.
   * @return category
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The category of the goal.")

  public List<CategorySummary88d272af423b100036e57ea69d570000> getCategory() {
    return category;
  }


  public void setCategory(List<CategorySummary88d272af423b100036e57ea69d570000> category) {
    
    
    
    this.category = category;
  }


  public GoalsSummary2c793e888bcd100033e663075a2b0000 supports(Supports9df8579a128710001ac8e9879d1f0000 supports) {
    
    
    
    
    this.supports = supports;
    return this;
  }

   /**
   * Get supports
   * @return supports
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Supports9df8579a128710001ac8e9879d1f0000 getSupports() {
    return supports;
  }


  public void setSupports(Supports9df8579a128710001ac8e9879d1f0000 supports) {
    
    
    
    this.supports = supports;
  }


  public GoalsSummary2c793e888bcd100033e663075a2b0000 worker(Worker47e98fa91eee100017c2c78c80410000 worker) {
    
    
    
    
    this.worker = worker;
    return this;
  }

   /**
   * Get worker
   * @return worker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Worker47e98fa91eee100017c2c78c80410000 getWorker() {
    return worker;
  }


  public void setWorker(Worker47e98fa91eee100017c2c78c80410000 worker) {
    
    
    
    this.worker = worker;
  }


  public GoalsSummary2c793e888bcd100033e663075a2b0000 status(Status9df8579a128710001ac8e9879d1f0001 status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Status9df8579a128710001ac8e9879d1f0001 getStatus() {
    return status;
  }


  public void setStatus(Status9df8579a128710001ac8e9879d1f0001 status) {
    
    
    
    this.status = status;
  }


  public GoalsSummary2c793e888bcd100033e663075a2b0000 completedOn(LocalDate completedOn) {
    
    
    
    
    this.completedOn = completedOn;
    return this;
  }

   /**
   * The date when the goal is completed.
   * @return completedOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date when the goal is completed.")

  public LocalDate getCompletedOn() {
    return completedOn;
  }


  public void setCompletedOn(LocalDate completedOn) {
    
    
    
    this.completedOn = completedOn;
  }


  public GoalsSummary2c793e888bcd100033e663075a2b0000 createdBy(CreatedBy88d272af423b100036b561a7784b0000 createdBy) {
    
    
    
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CreatedBy88d272af423b100036b561a7784b0000 getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(CreatedBy88d272af423b100036b561a7784b0000 createdBy) {
    
    
    
    this.createdBy = createdBy;
  }


  public GoalsSummary2c793e888bcd100033e663075a2b0000 state(String state) {
    
    
    
    
    this.state = state;
    return this;
  }

   /**
   * The state of the goal. Indicates why the goal is non-editable or why a user needs to take an action to successfully create or update the goal. Possible values: Pending approval, Associated with In Progress Review, Pending archival, Pending restore, Saved for later, and Needs revising.
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The state of the goal. Indicates why the goal is non-editable or why a user needs to take an action to successfully create or update the goal. Possible values: Pending approval, Associated with In Progress Review, Pending archival, Pending restore, Saved for later, and Needs revising.")

  public String getState() {
    return state;
  }


  public void setState(String state) {
    
    
    
    this.state = state;
  }


  public GoalsSummary2c793e888bcd100033e663075a2b0000 id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Id of the instance
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Id of the instance")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GoalsSummary2c793e888bcd100033e663075a2b0000 instance itself
   */
  public GoalsSummary2c793e888bcd100033e663075a2b0000 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoalsSummary2c793e888bcd100033e663075a2b0000 goalsSummary2c793e888bcd100033e663075a2b0000 = (GoalsSummary2c793e888bcd100033e663075a2b0000) o;
    return Objects.equals(this.description, goalsSummary2c793e888bcd100033e663075a2b0000.description) &&
        Objects.equals(this.name, goalsSummary2c793e888bcd100033e663075a2b0000.name) &&
        Objects.equals(this.relatesTo, goalsSummary2c793e888bcd100033e663075a2b0000.relatesTo) &&
        Objects.equals(this.activityStreamableItem, goalsSummary2c793e888bcd100033e663075a2b0000.activityStreamableItem) &&
        Objects.equals(this.dueDate, goalsSummary2c793e888bcd100033e663075a2b0000.dueDate) &&
        Objects.equals(this.associatedReviews, goalsSummary2c793e888bcd100033e663075a2b0000.associatedReviews) &&
        Objects.equals(this.category, goalsSummary2c793e888bcd100033e663075a2b0000.category) &&
        Objects.equals(this.supports, goalsSummary2c793e888bcd100033e663075a2b0000.supports) &&
        Objects.equals(this.worker, goalsSummary2c793e888bcd100033e663075a2b0000.worker) &&
        Objects.equals(this.status, goalsSummary2c793e888bcd100033e663075a2b0000.status) &&
        Objects.equals(this.completedOn, goalsSummary2c793e888bcd100033e663075a2b0000.completedOn) &&
        Objects.equals(this.createdBy, goalsSummary2c793e888bcd100033e663075a2b0000.createdBy) &&
        Objects.equals(this.state, goalsSummary2c793e888bcd100033e663075a2b0000.state) &&
        Objects.equals(this.id, goalsSummary2c793e888bcd100033e663075a2b0000.id)&&
        Objects.equals(this.additionalProperties, goalsSummary2c793e888bcd100033e663075a2b0000.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, name, relatesTo, activityStreamableItem, dueDate, associatedReviews, category, supports, worker, status, completedOn, createdBy, state, id, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoalsSummary2c793e888bcd100033e663075a2b0000 {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    relatesTo: ").append(toIndentedString(relatesTo)).append("\n");
    sb.append("    activityStreamableItem: ").append(toIndentedString(activityStreamableItem)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    associatedReviews: ").append(toIndentedString(associatedReviews)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    supports: ").append(toIndentedString(supports)).append("\n");
    sb.append("    worker: ").append(toIndentedString(worker)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    completedOn: ").append(toIndentedString(completedOn)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("name");
    openapiFields.add("relatesTo");
    openapiFields.add("activityStreamableItem");
    openapiFields.add("dueDate");
    openapiFields.add("associatedReviews");
    openapiFields.add("category");
    openapiFields.add("supports");
    openapiFields.add("worker");
    openapiFields.add("status");
    openapiFields.add("completedOn");
    openapiFields.add("createdBy");
    openapiFields.add("state");
    openapiFields.add("id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GoalsSummary2c793e888bcd100033e663075a2b0000
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GoalsSummary2c793e888bcd100033e663075a2b0000.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GoalsSummary2c793e888bcd100033e663075a2b0000 is not found in the empty JSON string", GoalsSummary2c793e888bcd100033e663075a2b0000.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("relatesTo") != null && !jsonObj.get("relatesTo").isJsonNull()) {
        JsonArray jsonArrayrelatesTo = jsonObj.getAsJsonArray("relatesTo");
        if (jsonArrayrelatesTo != null) {
          // ensure the json data is an array
          if (!jsonObj.get("relatesTo").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `relatesTo` to be an array in the JSON string but got `%s`", jsonObj.get("relatesTo").toString()));
          }

          // validate the optional field `relatesTo` (array)
          for (int i = 0; i < jsonArrayrelatesTo.size(); i++) {
            RelatesToSummary2c793e888bcd100034b42ada01b20000.validateJsonObject(jsonArrayrelatesTo.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("activityStreamableItem") != null && !jsonObj.get("activityStreamableItem").isJsonNull()) {
        JsonArray jsonArrayactivityStreamableItem = jsonObj.getAsJsonArray("activityStreamableItem");
        if (jsonArrayactivityStreamableItem != null) {
          // ensure the json data is an array
          if (!jsonObj.get("activityStreamableItem").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `activityStreamableItem` to be an array in the JSON string but got `%s`", jsonObj.get("activityStreamableItem").toString()));
          }

          // validate the optional field `activityStreamableItem` (array)
          for (int i = 0; i < jsonArrayactivityStreamableItem.size(); i++) {
            ActivityStreamableItemSummary88d272af423b100036fc19a90e210000.validateJsonObject(jsonArrayactivityStreamableItem.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("associatedReviews") != null && !jsonObj.get("associatedReviews").isJsonNull()) {
        JsonArray jsonArrayassociatedReviews = jsonObj.getAsJsonArray("associatedReviews");
        if (jsonArrayassociatedReviews != null) {
          // ensure the json data is an array
          if (!jsonObj.get("associatedReviews").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `associatedReviews` to be an array in the JSON string but got `%s`", jsonObj.get("associatedReviews").toString()));
          }

          // validate the optional field `associatedReviews` (array)
          for (int i = 0; i < jsonArrayassociatedReviews.size(); i++) {
            AssociatedReviewsSummary2c793e888bcd1000346e381955dd0000.validateJsonObject(jsonArrayassociatedReviews.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) {
        JsonArray jsonArraycategory = jsonObj.getAsJsonArray("category");
        if (jsonArraycategory != null) {
          // ensure the json data is an array
          if (!jsonObj.get("category").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `category` to be an array in the JSON string but got `%s`", jsonObj.get("category").toString()));
          }

          // validate the optional field `category` (array)
          for (int i = 0; i < jsonArraycategory.size(); i++) {
            CategorySummary88d272af423b100036e57ea69d570000.validateJsonObject(jsonArraycategory.get(i).getAsJsonObject());
          };
        }
      }
      // validate the optional field `supports`
      if (jsonObj.get("supports") != null && !jsonObj.get("supports").isJsonNull()) {
        Supports9df8579a128710001ac8e9879d1f0000.validateJsonObject(jsonObj.getAsJsonObject("supports"));
      }
      // validate the optional field `worker`
      if (jsonObj.get("worker") != null && !jsonObj.get("worker").isJsonNull()) {
        Worker47e98fa91eee100017c2c78c80410000.validateJsonObject(jsonObj.getAsJsonObject("worker"));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        Status9df8579a128710001ac8e9879d1f0001.validateJsonObject(jsonObj.getAsJsonObject("status"));
      }
      // validate the optional field `createdBy`
      if (jsonObj.get("createdBy") != null && !jsonObj.get("createdBy").isJsonNull()) {
        CreatedBy88d272af423b100036b561a7784b0000.validateJsonObject(jsonObj.getAsJsonObject("createdBy"));
      }
      if ((jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) && !jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GoalsSummary2c793e888bcd100033e663075a2b0000.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GoalsSummary2c793e888bcd100033e663075a2b0000' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GoalsSummary2c793e888bcd100033e663075a2b0000> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GoalsSummary2c793e888bcd100033e663075a2b0000.class));

       return (TypeAdapter<T>) new TypeAdapter<GoalsSummary2c793e888bcd100033e663075a2b0000>() {
           @Override
           public void write(JsonWriter out, GoalsSummary2c793e888bcd100033e663075a2b0000 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GoalsSummary2c793e888bcd100033e663075a2b0000 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             GoalsSummary2c793e888bcd100033e663075a2b0000 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GoalsSummary2c793e888bcd100033e663075a2b0000 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GoalsSummary2c793e888bcd100033e663075a2b0000
  * @throws IOException if the JSON string is invalid with respect to GoalsSummary2c793e888bcd100033e663075a2b0000
  */
  public static GoalsSummary2c793e888bcd100033e663075a2b0000 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GoalsSummary2c793e888bcd100033e663075a2b0000.class);
  }

 /**
  * Convert an instance of GoalsSummary2c793e888bcd100033e663075a2b0000 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

