/*
 * performanceEnablement
 * The Performance Management service enables applications to access and create feedback about workers in the system.
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BusinessProcessParameters2b4c8a6ca069100035b85907ae2c0000;
import com.konfigthis.client.model.FeedbackAbout2b4c8a6ca069100035b85907ae2c0002;
import com.konfigthis.client.model.FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000;
import com.konfigthis.client.model.FeedbackTemplate2b4c8a6ca069100035b859a141200001;
import com.konfigthis.client.model.RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf {
  public static final String SERIALIZED_NAME_FEEDBACK_ABOUT = "feedbackAbout";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_ABOUT)
  private FeedbackAbout2b4c8a6ca069100035b85907ae2c0002 feedbackAbout;

  public static final String SERIALIZED_NAME_FEEDBACK_CONFIDENTIAL = "feedbackConfidential";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_CONFIDENTIAL)
  private Boolean feedbackConfidential;

  public static final String SERIALIZED_NAME_FEEDBACK_OVERALL_STATUS = "feedbackOverallStatus";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_OVERALL_STATUS)
  private String feedbackOverallStatus;

  public static final String SERIALIZED_NAME_SHOW_FEEDBACK_PROVIDER_NAME = "showFeedbackProviderName";
  @SerializedName(SERIALIZED_NAME_SHOW_FEEDBACK_PROVIDER_NAME)
  private Boolean showFeedbackProviderName;

  public static final String SERIALIZED_NAME_REQUEST_DATE = "requestDate";
  @SerializedName(SERIALIZED_NAME_REQUEST_DATE)
  private LocalDate requestDate;

  public static final String SERIALIZED_NAME_EXPIRATION_DATE = "expirationDate";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_DATE)
  private LocalDate expirationDate;

  public static final String SERIALIZED_NAME_FEEDBACK_QUESTIONS = "feedbackQuestions";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_QUESTIONS)
  private List<RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000> feedbackQuestions = null;

  public static final String SERIALIZED_NAME_FEEDBACK_TEMPLATE = "feedbackTemplate";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_TEMPLATE)
  private FeedbackTemplate2b4c8a6ca069100035b859a141200001 feedbackTemplate;

  public static final String SERIALIZED_NAME_FEEDBACK_RESPONDERS = "feedbackResponders";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_RESPONDERS)
  private List<FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000> feedbackResponders = new ArrayList<>();

  public static final String SERIALIZED_NAME_BUSINESS_PROCESS_PARAMETERS = "businessProcessParameters";
  @SerializedName(SERIALIZED_NAME_BUSINESS_PROCESS_PARAMETERS)
  private BusinessProcessParameters2b4c8a6ca069100035b85907ae2c0000 businessProcessParameters;

  public static final String SERIALIZED_NAME_DESCRIPTOR = "descriptor";
  @SerializedName(SERIALIZED_NAME_DESCRIPTOR)
  private String descriptor;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf() {
  }

  
  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf(
     String feedbackOverallStatus, 
     LocalDate requestDate
  ) {
    this();
    this.feedbackOverallStatus = feedbackOverallStatus;
    this.requestDate = requestDate;
  }

  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf feedbackAbout(FeedbackAbout2b4c8a6ca069100035b85907ae2c0002 feedbackAbout) {
    
    
    
    
    this.feedbackAbout = feedbackAbout;
    return this;
  }

   /**
   * Get feedbackAbout
   * @return feedbackAbout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FeedbackAbout2b4c8a6ca069100035b85907ae2c0002 getFeedbackAbout() {
    return feedbackAbout;
  }


  public void setFeedbackAbout(FeedbackAbout2b4c8a6ca069100035b85907ae2c0002 feedbackAbout) {
    
    
    
    this.feedbackAbout = feedbackAbout;
  }


  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf feedbackConfidential(Boolean feedbackConfidential) {
    
    
    
    
    this.feedbackConfidential = feedbackConfidential;
    return this;
  }

   /**
   * Yes if the feedback is confidential between the feedback provider and the manager. Workers don&#39;t see confidential feedback.
   * @return feedbackConfidential
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Yes if the feedback is confidential between the feedback provider and the manager. Workers don't see confidential feedback.")

  public Boolean getFeedbackConfidential() {
    return feedbackConfidential;
  }


  public void setFeedbackConfidential(Boolean feedbackConfidential) {
    
    
    
    this.feedbackConfidential = feedbackConfidential;
  }


   /**
   * Overall status of the requested feedback process.
   * @return feedbackOverallStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "Overall status of the requested feedback process.")

  public String getFeedbackOverallStatus() {
    return feedbackOverallStatus;
  }




  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf showFeedbackProviderName(Boolean showFeedbackProviderName) {
    
    
    
    
    this.showFeedbackProviderName = showFeedbackProviderName;
    return this;
  }

   /**
   * Whether to display the name of the responders or have them remain anonymous.ccc
   * @return showFeedbackProviderName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Whether to display the name of the responders or have them remain anonymous.ccc")

  public Boolean getShowFeedbackProviderName() {
    return showFeedbackProviderName;
  }


  public void setShowFeedbackProviderName(Boolean showFeedbackProviderName) {
    
    
    
    this.showFeedbackProviderName = showFeedbackProviderName;
  }


   /**
   * The date the feedback request was initiated.
   * @return requestDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date the feedback request was initiated.")

  public LocalDate getRequestDate() {
    return requestDate;
  }




  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf expirationDate(LocalDate expirationDate) {
    
    
    
    
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * The date the feedback request expires.
   * @return expirationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date the feedback request expires.")

  public LocalDate getExpirationDate() {
    return expirationDate;
  }


  public void setExpirationDate(LocalDate expirationDate) {
    
    
    
    this.expirationDate = expirationDate;
  }


  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf feedbackQuestions(List<RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000> feedbackQuestions) {
    
    
    
    
    this.feedbackQuestions = feedbackQuestions;
    return this;
  }

  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf addFeedbackQuestionsItem(RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000 feedbackQuestionsItem) {
    if (this.feedbackQuestions == null) {
      this.feedbackQuestions = new ArrayList<>();
    }
    this.feedbackQuestions.add(feedbackQuestionsItem);
    return this;
  }

   /**
   * Feedback questions used in requested feedback events.
   * @return feedbackQuestions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Feedback questions used in requested feedback events.")

  public List<RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000> getFeedbackQuestions() {
    return feedbackQuestions;
  }


  public void setFeedbackQuestions(List<RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000> feedbackQuestions) {
    
    
    
    this.feedbackQuestions = feedbackQuestions;
  }


  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf feedbackTemplate(FeedbackTemplate2b4c8a6ca069100035b859a141200001 feedbackTemplate) {
    
    
    
    
    this.feedbackTemplate = feedbackTemplate;
    return this;
  }

   /**
   * Get feedbackTemplate
   * @return feedbackTemplate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FeedbackTemplate2b4c8a6ca069100035b859a141200001 getFeedbackTemplate() {
    return feedbackTemplate;
  }


  public void setFeedbackTemplate(FeedbackTemplate2b4c8a6ca069100035b859a141200001 feedbackTemplate) {
    
    
    
    this.feedbackTemplate = feedbackTemplate;
  }


  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf feedbackResponders(List<FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000> feedbackResponders) {
    
    
    
    
    this.feedbackResponders = feedbackResponders;
    return this;
  }

  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf addFeedbackRespondersItem(FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000 feedbackRespondersItem) {
    this.feedbackResponders.add(feedbackRespondersItem);
    return this;
  }

   /**
   * The respondents who&#39;ve been requested to provide feedback.
   * @return feedbackResponders
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The respondents who've been requested to provide feedback.")

  public List<FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000> getFeedbackResponders() {
    return feedbackResponders;
  }


  public void setFeedbackResponders(List<FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000> feedbackResponders) {
    
    
    
    this.feedbackResponders = feedbackResponders;
  }


  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf businessProcessParameters(BusinessProcessParameters2b4c8a6ca069100035b85907ae2c0000 businessProcessParameters) {
    
    
    
    
    this.businessProcessParameters = businessProcessParameters;
    return this;
  }

   /**
   * Get businessProcessParameters
   * @return businessProcessParameters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BusinessProcessParameters2b4c8a6ca069100035b85907ae2c0000 getBusinessProcessParameters() {
    return businessProcessParameters;
  }


  public void setBusinessProcessParameters(BusinessProcessParameters2b4c8a6ca069100035b85907ae2c0000 businessProcessParameters) {
    
    
    
    this.businessProcessParameters = businessProcessParameters;
  }


  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf descriptor(String descriptor) {
    
    
    
    
    this.descriptor = descriptor;
    return this;
  }

   /**
   * A preview of the instance
   * @return descriptor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit ame", value = "A preview of the instance")

  public String getDescriptor() {
    return descriptor;
  }


  public void setDescriptor(String descriptor) {
    
    
    
    this.descriptor = descriptor;
  }


  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Id of the instance
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Id of the instance")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf instance itself
   */
  public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf = (RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf) o;
    return Objects.equals(this.feedbackAbout, requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.feedbackAbout) &&
        Objects.equals(this.feedbackConfidential, requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.feedbackConfidential) &&
        Objects.equals(this.feedbackOverallStatus, requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.feedbackOverallStatus) &&
        Objects.equals(this.showFeedbackProviderName, requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.showFeedbackProviderName) &&
        Objects.equals(this.requestDate, requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.requestDate) &&
        Objects.equals(this.expirationDate, requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.expirationDate) &&
        Objects.equals(this.feedbackQuestions, requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.feedbackQuestions) &&
        Objects.equals(this.feedbackTemplate, requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.feedbackTemplate) &&
        Objects.equals(this.feedbackResponders, requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.feedbackResponders) &&
        Objects.equals(this.businessProcessParameters, requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.businessProcessParameters) &&
        Objects.equals(this.descriptor, requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.descriptor) &&
        Objects.equals(this.id, requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.id)&&
        Objects.equals(this.additionalProperties, requestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feedbackAbout, feedbackConfidential, feedbackOverallStatus, showFeedbackProviderName, requestDate, expirationDate, feedbackQuestions, feedbackTemplate, feedbackResponders, businessProcessParameters, descriptor, id, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf {\n");
    sb.append("    feedbackAbout: ").append(toIndentedString(feedbackAbout)).append("\n");
    sb.append("    feedbackConfidential: ").append(toIndentedString(feedbackConfidential)).append("\n");
    sb.append("    feedbackOverallStatus: ").append(toIndentedString(feedbackOverallStatus)).append("\n");
    sb.append("    showFeedbackProviderName: ").append(toIndentedString(showFeedbackProviderName)).append("\n");
    sb.append("    requestDate: ").append(toIndentedString(requestDate)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    feedbackQuestions: ").append(toIndentedString(feedbackQuestions)).append("\n");
    sb.append("    feedbackTemplate: ").append(toIndentedString(feedbackTemplate)).append("\n");
    sb.append("    feedbackResponders: ").append(toIndentedString(feedbackResponders)).append("\n");
    sb.append("    businessProcessParameters: ").append(toIndentedString(businessProcessParameters)).append("\n");
    sb.append("    descriptor: ").append(toIndentedString(descriptor)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("feedbackAbout");
    openapiFields.add("feedbackConfidential");
    openapiFields.add("feedbackOverallStatus");
    openapiFields.add("showFeedbackProviderName");
    openapiFields.add("requestDate");
    openapiFields.add("expirationDate");
    openapiFields.add("feedbackQuestions");
    openapiFields.add("feedbackTemplate");
    openapiFields.add("feedbackResponders");
    openapiFields.add("businessProcessParameters");
    openapiFields.add("descriptor");
    openapiFields.add("id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("feedbackResponders");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf is not found in the empty JSON string", RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `feedbackAbout`
      if (jsonObj.get("feedbackAbout") != null && !jsonObj.get("feedbackAbout").isJsonNull()) {
        FeedbackAbout2b4c8a6ca069100035b85907ae2c0002.validateJsonObject(jsonObj.getAsJsonObject("feedbackAbout"));
      }
      if ((jsonObj.get("feedbackOverallStatus") != null && !jsonObj.get("feedbackOverallStatus").isJsonNull()) && !jsonObj.get("feedbackOverallStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `feedbackOverallStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("feedbackOverallStatus").toString()));
      }
      if (jsonObj.get("feedbackQuestions") != null && !jsonObj.get("feedbackQuestions").isJsonNull()) {
        JsonArray jsonArrayfeedbackQuestions = jsonObj.getAsJsonArray("feedbackQuestions");
        if (jsonArrayfeedbackQuestions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("feedbackQuestions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `feedbackQuestions` to be an array in the JSON string but got `%s`", jsonObj.get("feedbackQuestions").toString()));
          }

          // validate the optional field `feedbackQuestions` (array)
          for (int i = 0; i < jsonArrayfeedbackQuestions.size(); i++) {
            RequestedFeedbackQuestionFfdd5de32f7f1000144df0c21e640000.validateJsonObject(jsonArrayfeedbackQuestions.get(i).getAsJsonObject());
          };
        }
      }
      // validate the optional field `feedbackTemplate`
      if (jsonObj.get("feedbackTemplate") != null && !jsonObj.get("feedbackTemplate").isJsonNull()) {
        FeedbackTemplate2b4c8a6ca069100035b859a141200001.validateJsonObject(jsonObj.getAsJsonObject("feedbackTemplate"));
      }
      // ensure the json data is an array
      if (!jsonObj.get("feedbackResponders").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `feedbackResponders` to be an array in the JSON string but got `%s`", jsonObj.get("feedbackResponders").toString()));
      }

      JsonArray jsonArrayfeedbackResponders = jsonObj.getAsJsonArray("feedbackResponders");
      // validate the required field `feedbackResponders` (array)
      for (int i = 0; i < jsonArrayfeedbackResponders.size(); i++) {
        FeedbackRespondersFfdd5de32f7f100016dbb1b188d70000.validateJsonObject(jsonArrayfeedbackResponders.get(i).getAsJsonObject());
      };
      // validate the optional field `businessProcessParameters`
      if (jsonObj.get("businessProcessParameters") != null && !jsonObj.get("businessProcessParameters").isJsonNull()) {
        BusinessProcessParameters2b4c8a6ca069100035b85907ae2c0000.validateJsonObject(jsonObj.getAsJsonObject("businessProcessParameters"));
      }
      if ((jsonObj.get("descriptor") != null && !jsonObj.get("descriptor").isJsonNull()) && !jsonObj.get("descriptor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `descriptor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("descriptor").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.class));

       return (TypeAdapter<T>) new TypeAdapter<RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf>() {
           @Override
           public void write(JsonWriter out, RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
  * @throws IOException if the JSON string is invalid with respect to RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf
  */
  public static RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf.class);
  }

 /**
  * Convert an instance of RequestedFeedbackOnWorkerEventDetail2b4c8a6ca069100035b8586e16c20000AllOf to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

